### ISSUE TITLE
Cannot initialize NetworkTables in physics without an error

### ISSUE THREAD

**Issue by virtuald** [robotpy/pyfrc#73]
Some reordering happened because of changes since last year, you end up with an error like this:

```
23:46:18:645 ERROR   : robotpy             : Could not instantiate robot MyRobot!
Traceback (most recent call last):
  File "robotpy-wpilib/wpilib/wpilib/robotbase.py", line 159, in main
    robot = robot_cls()
  File "robotpy-wpilib/wpilib/wpilib/robotbase.py", line 44, in __init__
    NetworkTables.setNetworkIdentity("Robot")
  File "pynetworktables/networktables/networktables.py", line 304, in setNetworkIdentity
    cls._checkInit()
  File "pynetworktables/networktables/networktables.py", line 129, in _checkInit
    raise RuntimeError("Network tables has already been initialized")
RuntimeError: Network tables has already been initialized

```

Should look at fixing it for 2018, as it's a bit annoying. Here's a workaround for anyone who has a physics module and needs to use NetworkTables:

```
    @property    
    def nt(self):
        try:
            return self._nt
        except AttributeError:
            self._nt = NetworkTable.getTable('/')
            return self._nt
```

**Comment by auscompgeek** [comment]
Is this still an issue this year, given that getTable no longer initialises NT?
